#!/usr/bin/env python3
"""AutoBVB Phase 2 — Multi-Process Integration Test (v2).

Verifies that the refactored worker.py successfully claims, processes,
and completes "approved" listings generated by the API pipeline.

v2 fixes from initial run:
  - Sets AUTOBVB_LOCAL_STORAGE so image paths resolve to local Windows paths
    instead of the Docker fallback (/app/local_storage).
  - Uses `python -u` for unbuffered subprocess output capture.
  - Runs e2e wrapper as a background process with concurrent listings.json
    monitoring, so we observe state transitions in real time.

Test sequence:
  1. Reset listings.json to empty state
  2. Launch API server (_verify_api:app) with AUTOBVB_LOCAL_STORAGE override
  3. Launch worker.py daemon for concurrent polling
  4. Pause for services to settle
  5. Launch _verify_e2e_wrapper.py (background) — generates draft → approves listing
  6. Concurrently monitor listings.json for worker state transitions
  7. Verify operational signatures, proof artifacts, and worker lifecycle
  8. Safe shutdown of ALL background processes via try/finally
"""

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────────────
PYTHON = r"C:\Users\Dell\AppData\Local\Programs\Python\Python313\python.exe"
PROJECT_DIR = Path(__file__).resolve().parent
LISTINGS_FILE = PROJECT_DIR / "listings.json"
LOCAL_STORAGE = PROJECT_DIR / "local_storage"
PROOFS_DIR = LOCAL_STORAGE / "proofs"
API_PORT = 8000

REAL_IMAGE = LOCAL_STORAGE / "flats01" / "flat1.jpg"
DUMMY_IMAGE = PROJECT_DIR / "dummy_flat.jpg"

SERVER_STARTUP_WAIT = 5
WORKER_STARTUP_WAIT = 3
E2E_TIMEOUT = 300               # max seconds for the e2e wrapper
MONITOR_TIMEOUT = 240            # max seconds to observe final state (includes e2e runtime)
MONITOR_INTERVAL = 2

REQUIRED_SIGNATURES = [
    "[Brain 1 - Vision] Extracting property metrics",
    "[Brain 1 - Vision] Extracted specs:",
    "Step 2: Generating AI Draft... PASS",
]

TERMINAL_STATUSES = {"completed", "shadow_success", "shadow_failed", "failed"}

# Build an environment dict that patches LOCAL_STORAGE for the API server.
# This ensures draft images are saved to the local workspace, not /app/.
_ENV = {**os.environ, "AUTOBVB_LOCAL_STORAGE": str(LOCAL_STORAGE), "PYTHONUNBUFFERED": "1"}


# ── Utilities ────────────────────────────────────────────────────────────────

def _port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(1)
        return s.connect_ex(("127.0.0.1", port)) == 0


def _drain_pipe(
    pipe, sink: list[str], label: str, stop: threading.Event,
) -> None:
    """Read lines from a subprocess pipe, storing and echoing live."""
    try:
        while not stop.is_set():
            line = pipe.readline()
            if not line:
                break
            sink.append(line)
            sys.stdout.write(f"  [{label}] {line}")
            sys.stdout.flush()
    except (ValueError, OSError):
        pass


def _kill_tree(pid: int) -> None:
    """Force-kill a Windows process tree (parent + all children)."""
    try:
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(pid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=10,
        )
    except Exception:
        pass


def _read_listings() -> list[dict]:
    if not LISTINGS_FILE.exists():
        return []
    try:
        with LISTINGS_FILE.open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def _find_listing_status(draft_id: str) -> str | None:
    for listing in _read_listings():
        if listing.get("id") == draft_id:
            return listing.get("status")
    return None


# ── Main Integration Test ────────────────────────────────────────────────────

def main() -> None:
    api_proc: subprocess.Popen | None = None
    worker_proc: subprocess.Popen | None = None
    e2e_proc: subprocess.Popen | None = None
    api_lines: list[str] = []
    worker_lines: list[str] = []
    e2e_lines: list[str] = []
    stop_event = threading.Event()

    print("=" * 72)
    print("  AutoBVB ✦ Phase 2 Multi-Process Integration Test (v2)")
    print("=" * 72)
    print(f"  Python          : {PYTHON}")
    print(f"  Project         : {PROJECT_DIR}")
    print(f"  API Port        : {API_PORT}")
    print(f"  Local Storage   : {LOCAL_STORAGE}")
    print(f"  Real Image      : {REAL_IMAGE}")
    print(f"  Monitor Timeout : {MONITOR_TIMEOUT}s")
    print(f"  Signatures      : {len(REQUIRED_SIGNATURES)}")
    print("=" * 72)

    try:
        # ── Step 1: Clean stale test data ────────────────────────────────
        print("\n[INT-TEST] Step 1 — Resetting listings.json to empty state...")
        LISTINGS_FILE.write_text("[]\n", encoding="utf-8")
        print("  ✓ listings.json reset to []")

        # Seed real property image for Brain 1 Vision analysis
        if REAL_IMAGE.is_file():
            shutil.copy2(REAL_IMAGE, DUMMY_IMAGE)
            print(f"  ✓ Seeded dummy_flat.jpg ({DUMMY_IMAGE.stat().st_size:,} bytes)")
        else:
            print(f"  ⚠ Real image not found at {REAL_IMAGE}")

        # ── Pre-flight port check ────────────────────────────────────────
        if _port_in_use(API_PORT):
            print(f"\n[INT-TEST] ABORT: Port {API_PORT} already in use.")
            sys.exit(1)

        # ── Step 2: Launch API server ────────────────────────────────────
        print(f"\n[INT-TEST] Step 2 — Launching API server on port {API_PORT}...")
        print(f"  AUTOBVB_LOCAL_STORAGE = {LOCAL_STORAGE}")
        api_proc = subprocess.Popen(
            [PYTHON, "-u", "-m", "uvicorn", "_verify_api:app",
             "--host", "0.0.0.0", "--port", str(API_PORT)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True, bufsize=1,
            encoding="utf-8", errors="replace",
            cwd=str(PROJECT_DIR),
            env=_ENV,
        )
        api_reader = threading.Thread(
            target=_drain_pipe,
            args=(api_proc.stdout, api_lines, "API", stop_event),
            daemon=True,
        )
        api_reader.start()
        print(f"  ✓ API server launched (PID {api_proc.pid})")

        # ── Step 3: Launch Worker daemon ─────────────────────────────────
        print("\n[INT-TEST] Step 3 — Launching worker.py daemon...")
        worker_proc = subprocess.Popen(
            [PYTHON, "-u", "worker.py"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True, bufsize=1,
            encoding="utf-8", errors="replace",
            cwd=str(PROJECT_DIR),
            env=_ENV,
        )
        worker_reader = threading.Thread(
            target=_drain_pipe,
            args=(worker_proc.stdout, worker_lines, "WORKER", stop_event),
            daemon=True,
        )
        worker_reader.start()
        print(f"  ✓ Worker daemon launched (PID {worker_proc.pid})")

        # ── Step 4: Wait for services to settle ─────────────────────────
        settle_wait = SERVER_STARTUP_WAIT + WORKER_STARTUP_WAIT
        print(f"\n[INT-TEST] Step 4 — Waiting {settle_wait}s for services to settle...")
        time.sleep(settle_wait)

        # Health checks
        if api_proc.poll() is not None:
            print(f"  ✗ API server exited prematurely (code {api_proc.returncode})")
            sys.exit(1)
        print(f"  ✓ API server running (PID {api_proc.pid})")

        if worker_proc.poll() is not None:
            print(f"  ⚠ Worker exited prematurely (code {worker_proc.returncode})")
        else:
            print(f"  ✓ Worker daemon running (PID {worker_proc.pid})")

        if _port_in_use(API_PORT):
            print(f"  ✓ Port {API_PORT} is listening")

        # ── Step 5: Launch e2e wrapper AS BACKGROUND (concurrent) ────────
        print("\n[INT-TEST] Step 5 — Launching _verify_e2e_wrapper.py in background "
              "(Two-Brain: Vision → Copywriter → Approve)...")
        e2e_proc = subprocess.Popen(
            [PYTHON, "-u", "_verify_e2e_wrapper.py"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True, bufsize=1,
            encoding="utf-8", errors="replace",
            cwd=str(PROJECT_DIR),
            env=_ENV,
        )
        e2e_reader = threading.Thread(
            target=_drain_pipe,
            args=(e2e_proc.stdout, e2e_lines, "E2E", stop_event),
            daemon=True,
        )
        e2e_reader.start()
        print(f"  ✓ e2e wrapper launched in background (PID {e2e_proc.pid})")

        # ── Step 6: Concurrent monitoring of listings.json ───────────────
        print(f"\n[INT-TEST] Step 6 — Concurrent monitoring of transaction ledger "
              f"(timeout {MONITOR_TIMEOUT}s)...")
        print("  Watching for: approved → processing → shadow_success | failed")

        deadline = time.monotonic() + MONITOR_TIMEOUT
        status_history: list[str] = []
        final_status: str | None = None
        draft_id: str | None = None

        while time.monotonic() < deadline:
            # Discover draft_id dynamically from e2e output
            if draft_id is None:
                for line in e2e_lines:
                    if "Draft ID:" in line:
                        draft_id = line.split("Draft ID:")[-1].strip()
                        print(f"  ℹ Draft ID discovered: {draft_id}")
                        break

            # Check status in listings.json
            current_status: str | None = None
            if draft_id:
                current_status = _find_listing_status(draft_id)
            else:
                # Fall back: look for any listing that was just created
                for listing in _read_listings():
                    s = listing.get("status")
                    if s:
                        current_status = s
                        draft_id = listing.get("id")
                        print(f"  ℹ Discovered listing via scan: {draft_id}")
                        break

            if current_status and (
                not status_history or status_history[-1] != current_status
            ):
                status_history.append(current_status)
                print(f"  → Status transition: {' → '.join(status_history)}")

            if current_status in TERMINAL_STATUSES:
                final_status = current_status
                print(f"  ✓ Terminal status reached: {final_status}")
                # Give the worker a moment to finish cleanup logging
                time.sleep(3)
                break

            # Check if both e2e and worker have exited (nothing more to observe)
            e2e_done = e2e_proc.poll() is not None
            worker_done = worker_proc.poll() is not None
            if e2e_done and worker_done and draft_id:
                final_status = _find_listing_status(draft_id)
                if final_status and (
                    not status_history or status_history[-1] != final_status
                ):
                    status_history.append(final_status)
                print(f"  ℹ Both e2e and worker have exited. "
                      f"Final status: {final_status}")
                break

            time.sleep(MONITOR_INTERVAL)
        else:
            print(f"  ⚠ Monitoring timed out after {MONITOR_TIMEOUT}s")
            if draft_id:
                final_status = _find_listing_status(draft_id)

        # ── Wait for e2e to finish if still running ──────────────────────
        if e2e_proc.poll() is None:
            print("\n  Waiting for e2e wrapper to finish (up to 60s)...")
            try:
                e2e_proc.wait(timeout=60)
            except subprocess.TimeoutExpired:
                print("  ⚠ e2e wrapper timed out — killing")
                _kill_tree(e2e_proc.pid)

        e2e_exit = e2e_proc.returncode
        print(f"  e2e exit code: {e2e_exit}")

        # ── Step 7: Check proof artifacts ────────────────────────────────
        print(f"\n[INT-TEST] Step 7 — Checking proof artifacts in {PROOFS_DIR}...")
        proof_found = False
        if PROOFS_DIR.is_dir():
            all_proofs = list(PROOFS_DIR.iterdir())
            if draft_id:
                matching = [p for p in all_proofs if draft_id in p.name]
                if matching:
                    for pf in matching:
                        print(f"  ✓ Proof file: {pf.name} "
                              f"({pf.stat().st_size:,} bytes)")
                        proof_found = True
                else:
                    print(f"  ⚠ No proof files matching draft {draft_id}")
                    if all_proofs:
                        print(f"  ℹ {len(all_proofs)} other proof file(s) exist")
            else:
                print(f"  ⚠ No draft_id available ({len(all_proofs)} total proofs)")
        else:
            print("  ⚠ Proofs directory does not exist")

        # ── Step 8: Signature verification ───────────────────────────────
        stop_event.set()
        time.sleep(0.5)
        api_log = "".join(api_lines)
        worker_log = "".join(worker_lines)
        e2e_out = "".join(e2e_lines)

        combined_log = "\n".join([e2e_out, api_log, worker_log])

        print(f"\n{'=' * 72}")
        print("[INT-TEST] Step 8 — Operational Signature Verification")
        print("=" * 72)

        missing: list[str] = []
        for sig in REQUIRED_SIGNATURES:
            if sig in combined_log:
                print(f"  ✅  FOUND   : {sig}")
            else:
                print(f"  ❌  MISSING : {sig}")
                missing.append(sig)

        # ── Worker lifecycle verification ────────────────────────────────
        print(f"\n{'=' * 72}")
        print("[INT-TEST] Worker Lifecycle Verification")
        print("=" * 72)
        print(f"  Draft ID       : {draft_id or 'N/A'}")
        print(f"  Status History : {' → '.join(status_history) if status_history else '(none observed)'}")
        print(f"  Final Status   : {final_status or 'N/A'}")
        print(f"  Proof Captured : {'Yes' if proof_found else 'No'}")

        # Check for key worker lifecycle events in the combined logs
        worker_claimed = "[Worker] Claimed approved listing" in worker_log
        worker_launched = "Launching stealth Chromium" in worker_log
        worker_navigated = "Navigating to https://www.facebook.com" in worker_log
        worker_composer = "Locating and opening the post composer" in worker_log
        worker_shadow = "SHADOW MODE" in worker_log
        worker_error = "[Worker] ERROR processing listing" in worker_log

        print(f"  Worker Claimed : {'Yes' if worker_claimed else 'No'}")
        print(f"  Browser Launch : {'Yes' if worker_launched else 'No'}")
        print(f"  FB Navigation  : {'Yes' if worker_navigated else 'No'}")
        print(f"  Composer Found : {'Yes' if worker_composer else 'No'}")
        print(f"  Shadow Mode    : {'Yes' if worker_shadow else 'No'}")
        print(f"  Error Logged   : {'Yes' if worker_error else 'No'}")

        # ── Worker log excerpt ───────────────────────────────────────────
        print(f"\n  --- Worker log (last 3000 chars) ---")
        if worker_log:
            print(worker_log[-3000:])
        else:
            print("  (no worker output captured)")
        print("  --- end worker log ---")

        # ── Final listings.json state ────────────────────────────────────
        final_listings = _read_listings()
        print(f"\n  --- Final listings.json ({len(final_listings)} entries) ---")
        for entry in final_listings:
            eid = entry.get("id", "?")
            estat = entry.get("status", "?")
            etext = entry.get("final_text", "")[:60]
            print(f"    {eid[:16]}... → status={estat}")
            print(f"      text: {etext}...")
            paths = entry.get("image_paths", [])
            for p in paths:
                exists = Path(p).is_file()
                print(f"      img: {p} ({'EXISTS' if exists else 'MISSING'})")
        print("  --- end listings ---")

        # ── Final Verdict ────────────────────────────────────────────────
        sigs_ok = len(missing) == 0
        claim_observed = "processing" in status_history or worker_claimed
        full_lifecycle = (
            "approved" in status_history
            and "processing" in status_history
        )

        print(f"\n{'=' * 72}")
        if sigs_ok and final_status == "shadow_success":
            print("  ✅  FULL INTEGRATION PASS")
            print("      Two-Brain pipeline + Worker shadow-mode round-trip verified")
        elif sigs_ok and full_lifecycle and final_status in TERMINAL_STATUSES:
            print(f"  ✅  INTEGRATION PASS — Worker lifecycle verified")
            print(f"      State machine: {' → '.join(status_history)}")
            if final_status == "failed":
                print("      Worker correctly handled a browser-interaction failure")
                print("      (expected: dummy credentials cannot authenticate to Facebook)")
        elif sigs_ok and claim_observed:
            print(f"  ⚠  PARTIAL PASS — Signatures OK, worker claimed listing")
            print(f"      Terminal status: {final_status}")
        elif sigs_ok:
            print(f"  ⚠  SIGNATURES PASS — Worker did not claim the listing")
        else:
            print(f"  ❌  INTEGRATION FAILED")
            print(f"      {len(missing)}/{len(REQUIRED_SIGNATURES)} signatures missing")
        print("=" * 72)

    finally:
        # ── Safe Shutdown ────────────────────────────────────────────────
        print("\n[INT-TEST] Safe shutdown — terminating ALL background processes...")
        stop_event.set()

        for label, proc in [
            ("E2E Wrapper", e2e_proc),
            ("Worker", worker_proc),
            ("API", api_proc),
        ]:
            if proc is None:
                continue
            if proc.poll() is None:
                print(f"  Terminating {label} (PID {proc.pid})...")
                try:
                    proc.terminate()
                    try:
                        proc.wait(timeout=5)
                        print(f"  ✓ {label} terminated cleanly")
                    except subprocess.TimeoutExpired:
                        print(f"  ⚠ {label} did not terminate — force-killing tree...")
                        _kill_tree(proc.pid)
                        print(f"  ✓ {label} force-killed")
                except Exception as e:
                    print(f"  ⚠ {label} cleanup error: {e}")
                    _kill_tree(proc.pid)
            else:
                print(f"  ✓ {label} already exited (code {proc.returncode})")

        print("\n[INT-TEST] All background processes cleaned up.")
        print("[INT-TEST] Integration test complete.\n")


if __name__ == "__main__":
    main()
